# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: safety
        name: Safety
        entry: poetry run safety --stage cicd scan --policy-file .safety-policy.yml
        pass_filenames: false
        language: system
