[tool.poetry]
name = "RCTAB_CLI"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8.0"
msal = "^1.11.0"
typer = "^0.4.1"
aiohttp = "^3.7.4"
pydantic = {extras = ["dotenv"], version = "^1.9.0"}
tabulate = "^0.8.9"
python-dateutil = "^2.8.2"
click = "8.0.4"
importlib = "^1.0.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
isort = "^5.8.0"
flake8 = "^5.0.4"
pylint = "^2.15.4"
mypy = "^0.931"
black = "^22.10"
pre-commit = "^2.15.0"
safety = "^2.3.1"

[tool.poetry.group.dev.dependencies]
pydocstyle = "^6.3.0"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
rctab =  "rctab_cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
