name: Release

on:
  release:
    types:
      - published

jobs:
  check_versions_match:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check that tag and package versions match
        run: |
          PYPROJECT_VERSION=$(sed -n '3p' pyproject.toml | sed "s/version = //")
          GITHUB_VERSION=${{ github.event.release.tag_name }}
          if [[ "$PYPROJECT_VERSION" != "\"$GITHUB_VERSION\"" ]]
          then
              echo "pyproject.toml version $PYPROJECT_VERSION doesn't match GitHub version \"$GITHUB_VERSION\""
              exit 1
          fi
